# -*- coding: utf-8 -*-
"""experiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJJu5nBIt6pGERxzY3rNVgmYt86bWuRT
"""


# -------------------------- #
# !python training_script.py    # %%writefile training_script.py
# ------------ YOU MIGHT NEED FACTORY RESET IN KAGGLE BETWEEN FAILED RUNS -------------- #

# # # DO FACTORY RESET
# # !pip uninstall -y pyarrow datasets
# !pip install -qU datasets transformers sympy pandas matplotlib pyarrow #<'15.0.0'
# # !pip install -qU datasets pyarrow tiktoken sympy pandas matplotlib
# !pip uninstall -y tensorflow
# !pip install -q tensorflow-cpu
# # # DO NORMAL RESTART

import os
import sys
import time
import math
import gc
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from transformers import get_cosine_schedule_with_warmup
from transformers import AutoTokenizer

# --- CRITICAL FIXES FOR KAGGLE TPU VM ---
os.environ["PJRT_DEVICE"] = "TPU"
os.environ["XLA_USE_BF16"] = "1"

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, IterableDataset
from datasets import load_dataset

# TPU IMPORTS
try:
    import torch_xla.core.xla_model as xm
    import torch_xla.distributed.parallel_loader as pl
    import torch_xla.distributed.xla_multiprocessing as xmp
except ImportError:
    print("TPU Not found. Please check your runtime.")
    sys.exit(1)

# ==========================================
# 1. CONFIGURATION
# ==========================================
class Config:
    # --- HYPERPARAMETERS ---
    dim = 512
    n_layers = 4
    n_heads = 8
    head_dim = 64
    hidden_dim = 2048
    vocab_size = 49152    # for smollm v2 tokenizer

    seq_len = 2048
    batch_size = 4            # Per Core (Total = batch_size * 8)
    learning_rate = 8e-4      # 1e-3 or 8e-4 or 3e-4
    weight_decay = 0.1
    warmup_steps = 1000
    min_lr = 8e-5

    total_time_limit_hours = 19.5
    val_steps = 50          # Number of evals during validation
    eval_interval = 500
    max_steps = 20_000

    # --- ARCHITECTURAL FLAGS ---
    # VAE / Hybrid Settings
    vae_linear_rank = 128
    vae_beta = 0.001

    # Stability
    use_grad_clip = False
    output_dir = "experiment_results"

    # --- SURGICAL ARCHITECTURE SWITCHES ---
    # Default: Only O (Attn Output) and Down (MLP Output) are Hybrid.
    # The training loop will override these for the Baseline run.

    # Attention Projections
    hybrid_q = True
    hybrid_k = True
    hybrid_v = True
    hybrid_o = False   # <--- DEFAULT HYBRID

    # MLP Projections
    hybrid_gate = True
    hybrid_up   = True
    hybrid_down = False  # <--- DEFAULT HYBRID

def set_seed(seed=42):
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

def get_model_infos(model):
    """Calculates model size in MB and parameter count."""
    param_size = 0
    num_params = 0
    for param in model.parameters():
        num_params += param.numel()
        param_size += param.nelement() * param.element_size()
    size_mb = param_size / 1024**2
    return size_mb, num_params

# ==========================================
# 2. MATH HELPERS & SHARED LAYERS
# ==========================================

class RMSNorm(nn.Module):
    def __init__(self, dim, eps=1e-6):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim))

    def forward(self, x):
        var = torch.mean(x ** 2, dim=-1, keepdim=True)
        x_normed = x * torch.rsqrt(var + self.eps)
        return self.weight * x_normed

def geometric_jsd_loss(mu, logvar):
    """
    The Geometric Jensen-Shannon Divergence Proxy.
    """
    var = torch.exp(logvar)
    kl_div = -0.5 * torch.sum(1 + logvar - mu.pow(2) - var, dim=-1)
    return torch.clamp(kl_div, max=0.693).mean()


# ==========================================
# 3. LINEAR LAYERS (HYBRID & STANDARD WRAPPER)
# ==========================================

class StandardLinearWrapper(nn.Module):
    """
    Wraps a standard nn.Linear to match the signature of HybridDualPathLinear.
    Returns: (output, 0.0)
    """
    def __init__(self, in_features, out_features, bias=False, **kwargs):
        super().__init__()
        self.linear = nn.Linear(in_features, out_features, bias=bias)

    def forward(self, x):
        return self.linear(x), 0.0

class HybridDualPathLinear(nn.Module):
    """
    Topology-Corrected Projection.
    Path 1: Block-Diagonal (Full Rank, Local)
    Path 2: Variational (Low Rank, Global)
    """
    def __init__(self, in_features, out_features, latent_dim, beta=0.01, num_blocks=4, **kwargs):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.beta = beta

        # --- PATH 1: The "Detail" Path (Block-Diagonal) ---
        self.groups = num_blocks
        if in_features % self.groups != 0 or out_features % self.groups != 0:
            self.groups = 1

        self.block_path = nn.Conv1d(
            in_channels=in_features,
            out_channels=out_features,
            kernel_size=1,
            groups=self.groups,
            bias=False
        )

        # --- PATH 2: The "Context" Path (Global VAE) ---
        self.vae_rank = latent_dim
        self.enc_mu = nn.Linear(in_features, latent_dim)
        self.enc_logvar = nn.Linear(in_features, latent_dim)
        self.decoder = nn.Linear(latent_dim, out_features, bias=False)

        # --- Initialization ---
        if self.in_features == self.out_features:
            nn.init.dirac_(self.block_path.weight)
            with torch.no_grad():
                self.block_path.weight.add_(torch.randn_like(self.block_path.weight) * 0.01)
        else:
            nn.init.orthogonal_(self.block_path.weight)

        nn.init.orthogonal_(self.enc_mu.weight)
        nn.init.zeros_(self.enc_logvar.weight)
        nn.init.orthogonal_(self.decoder.weight)

    def forward(self, x):
        # x: [Batch, Len, Dim]

        # --- Path 1: Block Diagonal ---
        x_perm = x.transpose(1, 2)
        detail_out = self.block_path(x_perm)
        detail_out = detail_out.transpose(1, 2)

        # --- Path 2: VAE ---
        mu = self.enc_mu(x)
        logvar = self.enc_logvar(x)

        if self.training:
            std = torch.exp(0.5 * logvar)
            eps = torch.randn_like(std)
            z = mu + eps * std
            loss = geometric_jsd_loss(mu, logvar) * self.beta
        else:
            z = mu
            loss = 0.0

        context_out = self.decoder(F.silu(z))

        out = detail_out + context_out
        return out, loss

def build_linear(in_dim, out_dim, is_hybrid, config):
    """Factory function to choose between Standard and Hybrid layers."""
    if is_hybrid:
        return HybridDualPathLinear(
            in_dim,
            out_dim,
            latent_dim=config.vae_linear_rank,
            beta=config.vae_beta,
            num_blocks=8 # Default block count
        )
    else:
        return StandardLinearWrapper(in_dim, out_dim, bias=False)

# ==========================================
# 4. SURGICAL ATTENTION & MLP
# ==========================================

class LlamaRotaryEmbedding(nn.Module):
    def __init__(self, dim, max_position_embeddings=32768, base=500000.0):
        super().__init__()
        inv_freq = 1.0 / (base ** (torch.arange(0, dim, 2).float() / dim))
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.max_seq_len_cached = max_position_embeddings
        t = torch.arange(self.max_seq_len_cached, dtype=torch.float32)
        freqs = torch.outer(t, self.inv_freq)
        emb = torch.cat((freqs, freqs), dim=-1)
        self.register_buffer("cos_cached", emb.cos(), persistent=False)
        self.register_buffer("sin_cached", emb.sin(), persistent=False)

    def forward(self, x, seq_len):
        if seq_len > self.max_seq_len_cached:
            self.__init__(x.shape[-1], max_position_embeddings=seq_len*2)
            self.to(x.device)
        return self.cos_cached[:seq_len, ...].to(x.dtype), self.sin_cached[:seq_len, ...].to(x.dtype)

def apply_rotary_pos_emb(q, k, cos, sin):
    def rotate_half(x): return torch.cat((-x[..., x.shape[-1]//2:], x[..., :x.shape[-1]//2]), dim=-1)
    cos, sin = cos[None, None, :, :], sin[None, None, :, :]
    return (q * cos) + (rotate_half(q) * sin), (k * cos) + (rotate_half(k) * sin)


class SurgicalAttention(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.n_heads = config.n_heads
        self.head_dim = config.head_dim
        dim = config.dim
        out_dim = config.n_heads * config.head_dim

        # Surgically instantiate based on Config flags
        self.q_proj = build_linear(dim, out_dim, config.hybrid_q, config)
        self.k_proj = build_linear(dim, out_dim, config.hybrid_k, config)
        self.v_proj = build_linear(dim, out_dim, config.hybrid_v, config)
        self.o_proj = build_linear(out_dim, dim, config.hybrid_o, config)

        self.rotary = LlamaRotaryEmbedding(config.head_dim)

    def forward(self, x):
        B, L, _ = x.shape

        # 1. Project Q, K, V (returns value, loss)
        q_flat, q_loss = self.q_proj(x)
        k_flat, k_loss = self.k_proj(x)
        v_flat, v_loss = self.v_proj(x)

        q = q_flat.view(B, L, self.n_heads, self.head_dim).transpose(1, 2)
        k = k_flat.view(B, L, self.n_heads, self.head_dim).transpose(1, 2)
        v = v_flat.view(B, L, self.n_heads, self.head_dim).transpose(1, 2)

        cos, sin = self.rotary(v, L)
        q, k = apply_rotary_pos_emb(q, k, cos, sin)

        attn_out = F.scaled_dot_product_attention(q, k, v, is_causal=True)
        attn_out = attn_out.transpose(1, 2).contiguous().view(B, L, -1)

        final_out, o_loss = self.o_proj(attn_out)

        total_aux_loss = q_loss + k_loss + v_loss + o_loss
        return final_out, total_aux_loss

class SurgicalMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        # Surgically instantiate based on Config flags
        self.gate_proj = build_linear(config.dim, config.hidden_dim, config.hybrid_gate, config)
        self.up_proj   = build_linear(config.dim, config.hidden_dim, config.hybrid_up,   config)
        self.down_proj = build_linear(config.hidden_dim, config.dim, config.hybrid_down, config)

    def forward(self, x):
        gate_out, gate_loss = self.gate_proj(x)
        gate_out = F.silu(gate_out)

        up_out, up_loss = self.up_proj(x)

        intermediate = gate_out * up_out

        down_out, down_loss = self.down_proj(intermediate)

        return down_out, gate_loss + up_loss + down_loss

# ==========================================
# 5. MODEL WRAPPER
# ==========================================

class GenModel(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.token_emb = nn.Embedding(config.vocab_size, config.dim)

        self.layers = nn.ModuleList()

        for _ in range(config.n_layers):
            # We always use Surgical classes; they adapt based on the Config
            self.layers.append(nn.ModuleDict({
                'norm1': RMSNorm(config.dim),
                'attn': SurgicalAttention(config),
                'norm2': RMSNorm(config.dim),
                'mlp': SurgicalMLP(config)
            }))

        self.norm = RMSNorm(config.dim)
        self.lm_head = nn.Linear(config.dim, config.vocab_size, bias=False)
        self.token_emb.weight = self.lm_head.weight

    def forward(self, idx, targets=None, step=None):
        B, L = idx.shape
        x = self.token_emb(idx)

        total_aux_loss = 0.0

        # 2. Transformer Blocks
        for layer in self.layers:
            # Attn
            norm_x = layer['norm1'](x)
            attn_out, attn_loss = layer['attn'](norm_x)
            x = x + attn_out
            total_aux_loss += attn_loss

            # MLP
            norm_x = layer['norm2'](x)
            mlp_out, mlp_loss = layer['mlp'](norm_x)
            x = x + mlp_out
            total_aux_loss += mlp_loss

        x = self.norm(x)
        logits = self.lm_head(x)

        final_loss = None
        if targets is not None:
            # Calculate Cross Entropy
            ce_loss = F.cross_entropy(logits.view(-1, logits.size(-1)), targets.view(-1))
            final_loss = ce_loss + total_aux_loss

        return logits, final_loss

# ==========================================
# 6. DATASET HANDLING
# ==========================================

class InfiniteTextDataset(IterableDataset):
    def __init__(self, seq_len, skip_tokens=0):
        self.seq_len = seq_len
        self.tokenizer = AutoTokenizer.from_pretrained("HuggingFaceTB/SmolLM2-135M")
        self.dataset = load_dataset("HuggingFaceFW/fineweb-edu", name="default", split="train", streaming=True)
        if skip_tokens == 0:
            self.dataset = self.dataset.take(10_000)
        else:
            self.dataset = self.dataset.skip(skip_tokens)
            self.dataset = self.dataset.shuffle(seed=42, buffer_size=10_000)

    def __iter__(self):
        buffer = []
        for sample in self.dataset:
            tokens = self.tokenizer.encode(sample['text'], add_special_tokens=False, truncation=True, max_length=8192)
            tokens.append(self.tokenizer.eos_token_id)
            buffer.extend(tokens)
            while len(buffer) >= self.seq_len + 1:
                chunk = buffer[:self.seq_len + 1]
                buffer = buffer[self.seq_len + 1:]
                yield {
                    "input_ids": torch.tensor(chunk[:-1], dtype=torch.long),
                    "labels": torch.tensor(chunk[1:], dtype=torch.long)
                }


def _mp_fn(index):
    torch.manual_seed(42)
    device = xm.xla_device()

    # --- DEFINE THE TWO RUNS ---
    # Run 1: Pure Baseline
    # Run 2: Surgical Hybrid (Default: O and Down)
    run_configs = ["Surgical_Method", "Baseline", ]

    global_start = time.time()
    time_limit_sec = Config.total_time_limit_hours * 3600
    budget_per_model = time_limit_sec / len(run_configs)

    xm.master_print(">>> Initializing Global Training Iterator...")
    train_ds = InfiniteTextDataset(Config.seq_len, skip_tokens=10_000)
    train_loader = DataLoader(train_ds, batch_size=Config.batch_size, num_workers=0, drop_last=True)
    para_train_loader = pl.MpDeviceLoader(train_loader, device)
    train_iterator = iter(para_train_loader)

    val_ds = InfiniteTextDataset(Config.seq_len, skip_tokens=0)
    val_loader = DataLoader(val_ds, batch_size=Config.batch_size, num_workers=0, drop_last=True)

    all_results = {}

    for run_name in run_configs:
        xm.master_print(f"\n\n>>> STARTING TRAINING: {run_name.upper()} on TPU")

        # --- CONFIGURE LAYERS SURGICALLY ---
        if run_name == "Baseline":
            # FORCE ALL STANDARD
            Config.hybrid_q = False
            Config.hybrid_k = False
            Config.hybrid_v = False
            Config.hybrid_o = False
            Config.hybrid_gate = False
            Config.hybrid_up = False
            Config.hybrid_down = False

        # elif run_name == "Surgical_Method":
        #     # --- USER CONFIGURATION ZONE ---
        #     Uncomment lines below to enable hybrid on other components

        #     Config.hybrid_q = False     # Set True to make Wq hybrid
        #     Config.hybrid_k = False     # Set True to make Wk hybrid
        #     Config.hybrid_v = False     # Set True to make Wv hybrid
        #     Config.hybrid_o = True      # <--- ACTIVE (Default)

        #     Config.hybrid_gate = False  # Set True to make Gate hybrid
        #     Config.hybrid_up = False    # Set True to make Up hybrid
        #     Config.hybrid_down = True   # <--- ACTIVE (Default)
        #     # -------------------------------

        # Instantiate Model with current flags
        model = GenModel(Config).to(device)
        mb_size, param_count = get_model_infos(model)
        xm.master_print(f"Model: {run_name} | Size: {mb_size:.2f} MB | Params: {param_count:,}")

        # Log active hybrid layers
        if xm.is_master_ordinal():
            print(f"  > Hybrid Layers Active:")
            print(f"    Attn: Q={Config.hybrid_q}, K={Config.hybrid_k}, V={Config.hybrid_v}, O={Config.hybrid_o}")
            print(f"    MLP:  Gate={Config.hybrid_gate}, Up={Config.hybrid_up}, Down={Config.hybrid_down}")

        param_dict = {pn: p for pn, p in model.named_parameters() if p.requires_grad}
        decay_params = [p for n, p in param_dict.items() if p.dim() >= 2]
        nodecay_params = [p for n, p in param_dict.items() if p.dim() < 2]

        optim_groups = [
            {'params': decay_params, 'weight_decay': Config.weight_decay},
            {'params': nodecay_params, 'weight_decay': 0.0}
        ]
        optimizer = torch.optim.AdamW(optim_groups, lr=Config.learning_rate, betas=(0.9, 0.95))
        scheduler = get_cosine_schedule_with_warmup(
            optimizer,
            num_warmup_steps=Config.warmup_steps,
            num_training_steps=Config.max_steps
        )

        model.train()

        start_time = time.time()
        model_start_time = time.time()

        best_val_loss = float('inf')
        train_history = []
        val_history = []
        step_history = []
        current_ce_losses = []
        current_aux_losses = []

        try:
            for step in range(Config.max_steps):
                elapsed_global = time.time() - global_start
                elapsed_model = time.time() - model_start_time
                if elapsed_global > (time_limit_sec - 600):
                    xm.master_print("!!! GLOBAL TIME LIMIT APPROACHING. STOPPING. !!!")
                    break
                if elapsed_model > budget_per_model:
                    xm.master_print(f"!!! TIME LIMIT FOR {run_name} REACHED. !!!")
                    break

                try:
                    batch = next(train_iterator)
                except StopIteration:
                    xm.master_print("Iterator exhausted. Restarting...")
                    train_iterator = iter(para_train_loader)
                    batch = next(train_iterator)

                input_ids = batch['input_ids']
                labels = batch['labels']

                optimizer.zero_grad()
                logits, total_loss = model(input_ids, labels, step=step)

                with torch.no_grad():
                    ce_val = F.cross_entropy(logits.view(-1, logits.size(-1)), labels.view(-1)).item()
                    aux_val = total_loss.item() - ce_val
                    current_ce_losses.append(ce_val)
                    current_aux_losses.append(aux_val)

                total_loss.backward()

                if Config.use_grad_clip:
                    xm.reduce_gradients(optimizer)
                    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                    optimizer.step()
                else:
                    xm.optimizer_step(optimizer)

                scheduler.step()

                if step > 0 and step % Config.eval_interval == 0:
                    avg_ce = sum(current_ce_losses) / len(current_ce_losses)
                    avg_aux = sum(current_aux_losses) / len(current_aux_losses)
                    current_ce_losses = []
                    current_aux_losses = []

                    model.eval()
                    val_loss_accum = 0.0
                    val_count = 0

                    with torch.no_grad():
                        for i, val_batch in enumerate(val_loader):
                            if i >= Config.val_steps: break
                            v_input = val_batch['input_ids'].to(device)
                            v_labels = val_batch['labels'].to(device)
                            _, v_loss = model(v_input, v_labels)
                            val_loss_accum += v_loss.item()
                            val_count += 1

                    avg_val_loss = val_loss_accum / val_count if val_count > 0 else 0.0

                    if avg_val_loss < best_val_loss:
                        best_val_loss = avg_val_loss
                        xm.master_print(f"--> New Best Val Loss: {best_val_loss:.4f}. Saving Model...")
                        xm.save(model.state_dict(), f"{Config.output_dir}/best_model_{run_name}.pt")

                    train_history.append(avg_ce + avg_aux)
                    val_history.append(avg_val_loss)
                    step_history.append(step)

                    dt = time.time() - start_time
                    tok_sec = (Config.batch_size * Config.seq_len * 8 * Config.eval_interval) / dt

                    xm.master_print(
                        f"[{run_name}] Step {step} | "
                        f"CE: {avg_ce:.4f} | "
                        f"Aux: {avg_aux:.4f} | "
                        f"Val: {avg_val_loss:.4f} | "
                        f"Speed: {tok_sec:.0f} tok/s"
                    )

                    model.train()
                    start_time = time.time()

        except Exception as e:
            xm.master_print(f"ERR: Training loop crashed for {run_name}: {e}")
            import traceback
            traceback.print_exc()

        if xm.is_master_ordinal():
            try:
                plt.figure(figsize=(10, 6))
                plt.plot(step_history, train_history, label='Train Loss', alpha=0.7)
                plt.plot(step_history, val_history, label='Val Loss', linewidth=2)
                plt.title(f'{run_name} Training Curve')
                plt.xlabel('Steps')
                plt.ylabel('Loss')
                plt.legend()
                plt.grid(True, alpha=0.3)
                plt.savefig(f"{Config.output_dir}/plot_{run_name}.png")
                plt.close()
            except Exception as e:
                print(f"Plotting failed: {e}")

        all_results[run_name] = {
            "steps": step_history,
            "train": train_history,
            "val": val_history
        }

        del model
        del optimizer
        xm.mark_step()
        gc.collect()

    if xm.is_master_ordinal():
        try:
            plt.figure(figsize=(12, 8))
            colors = plt.cm.tab20(np.linspace(0, 1, len(all_results)))

            for i, (mode_name, data) in enumerate(all_results.items()):
                plt.plot(
                    data["steps"],
                    data["val"],
                    label=f'{mode_name} (Val)',
                    color=colors[i],
                    linewidth=2
                )

            plt.title('Comparison: Baseline vs Surgical Hybrid')
            plt.xlabel('Steps')
            plt.ylabel('Loss')
            plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
            plt.grid(True, alpha=0.3)
            plt.tight_layout()
            plt.savefig(f"{Config.output_dir}/final_comparison.png")
            plt.close()
        except Exception as e:
            print(f"Final plotting failed: {e}")


if __name__ == "__main__":
    if not os.path.exists(Config.output_dir):
        os.makedirs(Config.output_dir)

    xmp.spawn(_mp_fn, args=(), nprocs=1, start_method='spawn')

# !python training_script.py